name: Build and Push Frontend Image

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  REPOSITORY: spam-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v3

      - name: Ustaw VERSION = pierwsze 8 znaków SHA
        run: |
          echo "VERSION=$(echo ${GITHUB_SHA} | cut -c1-8)" >>"$GITHUB_ENV"

      - name: Log in do Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build i Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ env.REPOSITORY }}:latest
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ env.REPOSITORY }}:${{ env.VERSION }}

      - name: Wyświetl zbudowaną wersję
        run: |
          echo "Built frontend image tag: ${{ env.VERSION }}"
