name: Build Frontend Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'SHA tag'
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        description: 'Username Docker Hub'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Token Hub password'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repozytorium
        uses: actions/checkout@v3


      - name: Version from input
        run: |
          echo "VERSION=${{ inputs.image_tag }}" >>"$GITHUB_ENV"

      # —————— 3) Logowanie do Docker Huba (aby móc wypchnąć obraz) ——————
      - name: Log in do Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # —————— 4) Budowanie i wypychanie obrazu frontendowego ——————
      - name: Build i Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          # kontekst ustawiony na katalog z kodem klienta (spam-client)
          context: ./frontend/no-spam-client
          file: ./frontend/no-spam-client/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-client:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-client:${{ env.VERSION }}

      # —————— 5) (opcjonalnie) Wyświetlenie w logach, jakiego taga użyliśmy ——————
      - name: Wyświetl zbudowaną wersję
        run: |
          echo "Built frontend image tag: ${{ env.VERSION }}"
