name: Creating Spam-Client Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: A tag to apply (usually the commit SHA)
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push front-end image
        uses: docker/build-push-action@v3
        with:
          # point at your client folder
          context: ./frontend/no-spam-client
          file: ./frontend/no-spam-client/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-client:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-client:${{ inputs.image_tag }}

      - name: Confirm
        run: echo "Pushed front-end image with tag ${{ inputs.image_tag }}"
