name: Build Frontend Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Tag under which we will push the image (e.g. branch name or SHA)'
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        description: 'Docker Hub username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Docker Hub access token or password'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set VERSION from input
        run: |
          echo "VERSION=${{ inputs.image_tag }}" >>"$GITHUB_ENV"


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/no-spam-client
          file: ./frontend/no-spam-client/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-client:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-client:${{ env.VERSION }}


      - name: Display built version
        run: |
          echo "Built frontend image tag: ${{ env.VERSION }}"
