name: Creating Spam-Backend-Image

on:
  workflow_call:
    inputs:
      docker_username:
        required: true
        type: string
      docker_token:
        required: true
        type: string
      artifact_path:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: spam-model-artifacts
          path: ${{ inputs.artifact_path }}

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: docker.io
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_token }}

      - uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: |
            docker.io/${{ inputs.docker_username }}/spam-api:latest
            docker.io/${{ inputs.docker_username }}/spam-api:${{ inputs.image_tag }}

      - run: echo "Pushed image with tag ${{ inputs.image_tag }}"
