name: Build Backend Image

on:
  workflow_call:
    inputs:
      artifact_path:
        description: 'Path under which model artifacts are stored (relative to repo root)'
        required: true
        type: string
      image_tag:
        description: 'Raw tag string (e.g. branch name or SHA). Will be sanitized before use.'
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        description: 'Docker Hub username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Docker Hub access token or password'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: spam-model-artifacts
          path: ${{ inputs.artifact_path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanitize IMAGE_TAG (replace "/" with "-")
        id: sanitize
        run: |
          raw="${{ inputs.image_tag }}"
          SANITIZED_TAG="${raw//\//-}"
          echo "SANITIZED_TAG=$SANITIZED_TAG" >> "$GITHUB_ENV"

      - name: Debug sanitized tag
        run: |
          echo "Using sanitized tag: ${{ env.SANITIZED_TAG }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-api:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-api:${{ env.SANITIZED_TAG }}

      - name: Confirm
        run: |
          echo "Pushed image with tag: ${{ env.SANITIZED_TAG }}"
