name: Build Backend Image

on:
  workflow_call:
    inputs:
      artifact_path:
        description: 'Path under which model artifacts are stored (relative to repo root)'
        required: true
        type: string
      image_tag:
        description: 'Tag under which to push the backend image (e.g. branch-name-or-sha)'
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        description: 'Docker Hub username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Docker Hub access token or password'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: spam-model-artifacts
          path: ${{ inputs.artifact_path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug secrets
        shell: bash
        run: |
          echo "— Checking that DOCKERHUB_USER is set —"
          if [ -z "$DOCKERHUB_USER" ]; then
            echo "ERROR: DOCKERHUB_USER is empty!"
            exit 1
          fi
          echo "DOCKERHUB_USER is set (length: ${#DOCKERHUB_USER})"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-api:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/spam-api:${{ inputs.image_tag }}

      - name: Confirm
        run: |
          echo "Pushed image with tag: ${{ inputs.image_tag }}"
