name:  Train Spam Model

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest
    env:
      SACRED_OBSERVER_DIR: backend/sacred_runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run models training
        run: |
          python -m backend.model_training \

      - name: Select best hyperparameters
        run: |
          python -m backend.get_best_hyperparameters \
            --observer-dir ${{ env.SACRED_OBSERVER_DIR }} \
            --out-config backend/best_config.json

      - name: Train final model with best_config.json
        run: |
          python -m backend.train_best_model

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spam-model-artifacts
          path: |
            backend/best_config.json
            backend/best_model.pth
