name: Train Spam Model

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  retrain:
    runs-on: ubuntu-latest
    env:
      SACRED_OBSERVER_DIR: backend/sacred_runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run model training
        run: python -m backend.model_training

      - name: Select best hyperparameters
        run: |
          python -m backend.get_best_hyperparameters \
            --observer-dir ${{ env.SACRED_OBSERVER_DIR }} \
            --out-config backend/best_config.json

      - name: Train final model with best_config.json
        run: python -m backend.train_best_model

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spam-model-artifacts
          path: |
            backend/best_config.json
            backend/best_model.pth

  build-image:
    needs: retrain
    uses: ./.github/workflows/deploy-backend.yml
    with:
      artifact_path: backend/
      image_tag: ${{ github.head_ref }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}